//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Izvestava
    {
        public int ID_OZL { get; set; }
        public int PretpoletniPregledID_AV { get; set; }
        public int PretpoletniPregledID_AT { get; set; }
    
        public virtual OZL OZL { get; set; }
        public virtual PretpoletniPregled PretpoletniPregled { get; set; }
    }
}
