//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MilitaryAviationBaseContainer : DbContext
    {
        public MilitaryAviationBaseContainer()
            : base("name=MilitaryAviationBaseContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Radionica> Radionice { get; set; }
        public virtual DbSet<AvioTehnicar> AvioTehnicari { get; set; }
        public virtual DbSet<Eskadrila> Eskadrile { get; set; }
        public virtual DbSet<Avion> Avions { get; set; }
        public virtual DbSet<PretpoletniPregled> PretpoletniPregleds { get; set; }
        public virtual DbSet<Pilot> Pilots { get; set; }
        public virtual DbSet<OZL> OZLs { get; set; }
        public virtual DbSet<Izvestava> Izvestavas { get; set; }
        public virtual DbSet<Naoruzanje> Naoruzanjes { get; set; }
        public virtual DbSet<OC> OCs { get; set; }
        public virtual DbSet<Uzima> Uzimas { get; set; }
    }
}
