//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pilot
    {
        public int ID_PIL { get; set; }
        public string RN_PIL { get; set; }
        public Nullable<int> AvionID_AV { get; set; }
        public Nullable<int> OZLID_OZL { get; set; }
        public Nullable<int> EskadrilaID_ESK1 { get; set; }
    
        public virtual Avion Avion { get; set; }
        public virtual OZL OZL { get; set; }
        public virtual Eskadrila Eskadrila { get; set; }
    }
}
