//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uzima
    {
        public int OCID_OC { get; set; }
        public int NaoruzanjeLovacID_AV { get; set; }
        public int NaoruzanjeElektroOpremaVazduhoplovaID_AT { get; set; }
    
        public virtual OC OC { get; set; }
        public virtual Naoruzanje Naoruzanje { get; set; }
    }
}
